// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzmxhmyhjbiudbhegmpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6bXhobXloamJpdWRiaGVnbXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDQwNTIsImV4cCI6MjA3MDc4MDA1Mn0.349JGzLf8lnej1Tw7y2o0Uv9SZJT_nVnCVpiYKANz78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});